### ISSUE TITLE
How to start/stop camera

### ISSUE THREAD

**Issue by hjw1007** [ifm/ifm3d#115]
hi ,all 
  I can get image follow as this：

```cpp
auto cam = ifm3d::Camera::MakeShared();
  auto fg = std::make_shared<ifm3d::FrameGrabber>(cam);
  auto im = std::make_shared<ifm3d::ImageBuffer>();
  cv::Mat amp;
  cv::Mat xyz;
  while (true)
  {
    if (! fg->WaitForFrame(im.get(), 1000))
    {
      std::cerr << "Timeout waiting for camera!" << std::endl;
      return -1;
    }
    amp = im->AmplitudeImage();
    xyz = im->XYZImage();
   .....
  }
```

I can break program but don't stop camera, I want to start/stop camera in my free time. How can I deal with it ?

**Comment by graugans** [comment]
So this is due to the fact the camera delivers image data and the frame grabber waits for them. So to stop the camera from sending images you can switch to a different Trigger mode. For example software trigger or hardware trigger.
