### ISSUE TITLE
Why the depth map has the inverted reflection in a concrete ground？

### ISSUE THREAD

**Issue by JunLFang** [ifm/ifm3d#118]

**Comment by JunLFang** [comment]
![pcd](https://user-images.githubusercontent.com/31059614/48990885-51bdfb80-f16b-11e8-9b4b-0db34896e865.png)

**Comment by JunLFang** [comment]
How to solve the problem or avoid it? Thanks a lot.

**Comment by graugans** [comment]
@JunLFang to dig a bit more deeper into this problem we probably need more details. Nevertheless please keep in mind this is a camera with an active illumination. It looks like you are suffering from reflective materials which do act like a mirror.

**Comment by GarrettPlace** [comment]
@JunLFang  - thank you for the details provided.  As @graugans mentions, additional detail would be required to best support your questions.  It may also be helpful to understand your primary Use Case as this may help us direct you to the appropriate settings.  Would you like to do this offline or on this thread?

**Comment by theseankelly** [comment]
@JunLFang I'm going through and closing old issues -- please feel free to reactivate or reach out to @GarrettPlace directly and take him up on his offer to discuss offline.
