### ISSUE TITLE
O3D303 Repeatability accuracy

### ISSUE THREAD

**Issue by hjw1007** [ifm/ifm3d#121]
hi ,all
    I test four times in 3m work distance, each line represents the depth data of line 150 of the image,.Why is repeatability accuracy inconsistent at each point?

[150row_data.xlsx](https://github.com/ifm/ifm3d/files/2623509/150row_data.xlsx)

![image](https://user-images.githubusercontent.com/10862872/49137996-fc2f4d80-f328-11e8-8561-f0a3d02e4be6.png)

**Comment by graugans** [comment]
@hjw1007 thanks for your contribution, can you please provide a diagram descriptions in the English language. Additionally it would be very nice to have the plotted data in CSV so it is easier to read.

Could you please so kind and provide the following information:

- Recorded amplitude and distance data of the scene you are looking at.
- The firmware version you are running

**Comment by hjw1007** [comment]
@graugans Thank you for your quick answer.  I run in the firmware version is 1.6.2114 and the sensor is O3D303 and the ifm3d version is 0.11.1 and ubuntu version is 16.04LTS.
![38c9b647fd3f7eb722b1c4491dd7fe1](https://user-images.githubusercontent.com/10862872/49142961-ea53a780-f334-11e8-9874-efd0a1ba4163.png)
![amplitudeimage](https://user-images.githubusercontent.com/10862872/49144753-17a25480-f339-11e8-8014-8746c242d643.jpg)
![distanceimage](https://user-images.githubusercontent.com/10862872/49144755-18d38180-f339-11e8-8a4e-d1f0f7eff67f.jpg)

**Comment by theseankelly** [comment]
If I'm reading this plot correctly, the jitter observed is within the noise profile of the sensor.

That said, this issue is 1.5 years old so I'm closing it. Don't hesitate to reactivate if further assistance is required.
