### ISSUE TITLE
Pointcloud noise near the origin of the ifm o3d303 camera

### ISSUE THREAD

**Issue by srane96** [ifm/ifm3d#167]
Whenever I point my camera in the room where there are many objects, I get this kind of pyramid shaped noise near the origin.
![Screenshot from 2019-07-29 15-35-00](https://user-images.githubusercontent.com/42813193/62076900-d7240f00-b216-11e9-959e-fd068941ca09.png).
However when I point my camera in the direction of the wall or the ceiling I do not get any outliers/noise between origin and the point clouds associated with the wall/ceiling.

I am wondering what could be the reason of this pyramid shaped noise?  I am guessing it's due to reflections from the other objects in the surrounding. Am I right ? or is there any other reason that might be causing it?

Also, if it is due the reflections of the other objects, why is it forming near the camera lenses? is this any specific type of noise? what is it called?

**Comment by tpanzarella** [comment]
This looks like ambiguity range issues (standard ToF artifact). Likely, you are using an imager setting with a single frequency and increasing it to two frequencies may fix this issue. Please post the output of `$ ifm3d dump` and we can take a look to validate. If this is the case, we can give you a setting to eliminate this artifact.

**Comment by srane96** [comment]
Just clarifying. RAA is caused when 1st pulse reaches receiver after 2nd is transmitted, and sensor thinks that it is from the 2nd emitted pulse, right? So is this why you are suggesting me to increase the frequency?
Btw here is the config file.
[config.txt](https://github.com/ifm/ifm3d/files/3446828/config.txt)

**Comment by tpanzarella** [comment]
You are using a single frequency. The following command should fix your issue:

```
$ ifm3d dump | jq '.ifm3d.Apps[0].Imager.Type="upto30m_moderate"' | ifm3d config
```

This assumes you have `jq`. If you do not, you can `$ sudo apt install jq` or just edit your config.txt directly and `$ ifm3d config < config.txt`.

HTH.

**Comment by srane96** [comment]
Thank you so much!
