### ISSUE TITLE
basic_usage.md does not compile

### ISSUE THREAD

**Issue by lueiropablo** [ifm/ifm3d#168]
When I try to compile the ifm3d / doc / basic_usage.md example, it does not compile, throwing the error: fatal error: opencv2 / core / core.hpp: File or directory does not exist.

The ifm3d Library does not contain the opencv2 module. I bet that in some recent version of ifm3d said faith module replaced by the new opencv module.

**Comment by tpanzarella** [comment]
How do you try to compile it? Are your compiler flags set appropriately? Can you paste in: 1) your code; 2) how your building -- i.e., either the compiler line you are using or your `CMakeLists.txt` file if you are using CMake.

**Comment by lueiropablo** [comment]
I compile and building from Geany. 

I have only installed the binaries for ifm3d, following the instructions here https://github.com/ifm/ifm3d

Should I install all the Boost, Curl, Glog dependencies ... as explained here https://github.com/ifm/ifm3d/blob/master/doc/source_build.md?

The compiler complains in this line:  #include <opencv2 / core / core.hpp>

![ScreenClip](https://user-images.githubusercontent.com/53621980/62414766-78003900-b620-11e9-8196-acb893311410.png)

**Comment by tpanzarella** [comment]
You will need to install the opencv development files. In this case: `$ sudo apt install libopencv-core-dev`. You should be OK without Boost. You may need the Glog development files though: `$ sudo apt install libgoogle-glog-dev`.

**Comment by lueiropablo** [comment]
I have added all the dependencies:
```
sudo apt-get update && apt-get install -y libboost-all-dev git jq libcurl4-openssl-dev \
                                            libgtest-dev libgoogle-glog-dev  \
                                            libxmlrpc-c++8-dev libopencv-dev \
                                            libpcl-dev libproj-dev \
                                            build-essential coreutils cmake
```
almost ready .... but again ...

`/usr/include/ifm3d/image/image_buffer.h:25:10: fatal error: pcl/point_cloud.h: No such file or directory`
![ScreenClip](https://user-images.githubusercontent.com/53621980/62464591-4f498200-b78d-11e9-93a4-a56b04b1bb48.png)

pcl / point_tipes.h does not complain about the directory. The directory does exist ...
`/usr/include/pcl-1.8/pcl`

![ScreenClip](https://user-images.githubusercontent.com/53621980/62464825-e1ea2100-b78d-11e9-88a6-30b671ae23fc.png)

**Comment by tpanzarella** [comment]
Looks like you need to add `/usr/include/pcl-1.8` to your compiler's include path, typically something like `-I/usr/include/pcl-1.8`.

As a general comment, you may want to consider using CMake as a lot of this type of configuration is taken care of for you. YMMV.

**Comment by theseankelly** [comment]
Hi @lueiropablo, were you able to work through these issues or are you still having trouble compiling?
