### ISSUE TITLE
Where i can get the example code about the Integrating PDS ?

### ISSUE THREAD

**Issue by Silent-Souls** [ifm/ifm3d#171]
I found it in the link below, but I can't find additional information about this system.
https://www.ifm.com/us/en/us/robotics/software-solutions/pds/integrating-pds/integrating-pds
Thanks!

**Comment by Silent-Souls** [comment]
> Hi -- happy to help but we're currently handling PDS support internally rather than on GitHub. Could you shoot a mail to [Sean.Kelly@ifm.com](mailto:Sean.Kelly@ifm.com)?

Thank you so much,I will send you a mail soon.

**Comment by josephchen5** [comment]
Hello, I have an ifm TOF camera, the model is O3D303, I also cannot use PDS, how can I get support
https://www.ifm.com/us/en/us/robotics/software-solutions/pds/integrating-pds/integrating-pds
Thanks!

**Comment by graugans** [comment]
Hey @josephchen5 , you need a special device for PDS support. Please get in touch with @GarrettPlace
