### ISSUE TITLE
IFM3D O3D Firmware Compatibility

### ISSUE THREAD

**Issue by bryanIkeNextStep** [ifm/ifm3d#176]
Hello,

I noticed the compatibility matrix doesn't list firmware 1.30.4123 next to IFM3D version 0.16.0.  Does IFM3D version 0.16.0 support firmware 1.30.4123?

**Comment by theseankelly** [comment]
Yes it does, my apologies.

I'll leave this ticket open to track getting that compat matrix updated.

**Comment by theseankelly** [comment]
1.30.4123 was removed from the compat table by mistake in v0.16.0. We've reverted v0.16.0 entirely, and so this bug is resolved.
