### ISSUE TITLE
Downloading radial distances only

### ISSUE THREAD

**Issue by pfrydlewicz** [ifm/ifm3d#198]
Hi,
When masking the camera to provide only radial distances and amplitude, does the ifm3d library take care of calculating xyz?

Or do I need to program it by myself?

Thanks in advance.
Paul

**Comment by theseankelly** [comment]
The ifm3d library will not compute cartesian data offboard for you; you'll need to do it in your application code.

The unit tests for `Image` contain a reference implementation: https://github.com/ifm/ifm3d/blob/49ff0726a0e8170fb089b60f2a06c36734a3b7cd/modules/image/test/ifm3d-image-tests.cpp#L329

And here's a python reference implementation: https://github.com/ifm/ifm3d/blob/master/doc/compute_cartesian/O3D_Cartesian_Computation.ipynb
