### ISSUE TITLE
I need the library on Windows

### ISSUE THREAD

**Issue by swx954068967** [ifm/ifm3d#201]
I need the library on Windows,but  https://github.com/ifm/ifm3d  :
Windows
Coming soon...

When can you provide it?
Is this compilation scheme correct?It's a little difficult for me.I want to have compiled libraries, and interface documentation, like O3D SDK
https://github.com/ifm/ifm3d/blob/master/doc/windows.md

**Comment by theseankelly** [comment]
Hi @swx954068967 -- the "coming soon" string refers to making pre-compiled binaries available. The library does build and run on Windows, and the instructions you linked are the correct instructions.

Regarding the task of auto-generating and shipping pre-compiled binaries, this is on our backlog and I don't have a target date at this time.

**Comment by swx954068967** [comment]
Thanks for your reply.
Yes, I need the precompile driver on Windows, just like the 03D SDK.Compiling from source code is a bit difficult and time-consuming for me, and I've tried and failed, due to boost or VS versions.As a product for sale, I think it is necessary to provide precompiled libraries for common platforms. I look forward to it as soon as possible

**Comment by Arag24** [comment]
@swx954068967 : if you're interested with precompiled binaries VS 2017 64bit,
Please can you send me your email in PM, please?

**Comment by swx954068967** [comment]
> @swx954068967 : if you're interested with precompiled binaries VS 2017 64bit,
> Please can you send me your email in PM, please?

Thank you. My email is swx954068967@live.cn. Sorry for the late reply.

**Comment by theseankelly** [comment]
Hey @swx954068967 I've recorded your email and sent to @Arag24 internally. I have removed it from the message above for your privacy.

**Comment by Arag24** [comment]
@swx954068967 : Did you de receive, download and test package sir? Do you need something else ? Thanks for feedback.

**Comment by theseankelly** [comment]
@swx954068967 my understanding is @Arag24 has provided you the necessary binaries privately -- do reach out again if you require further assistance.
