### ISSUE TITLE
Is there any example of pallet detection?

### ISSUE THREAD

**Issue by GoodTekken** [ifm/ifm3d#228]
Hello, 
    Is there any example of pallet detection? Thank you.

[https://www.ifm.com/us/en/us/robotics/software-solutions/pds/integrating-pds/integrating-pds](https://www.ifm.com/us/en/us/robotics/software-solutions/pds/integrating-pds/integrating-pds)
[https://www.ifm.com/us/en/us/robotics/software-solutions/pds/pds](https://www.ifm.com/us/en/us/robotics/software-solutions/pds/pds)

**Comment by theseankelly** [comment]
Hey @GoodTekken -- our Pallet Detection System (PDS) solution itself proprietary. We have a few client interfaces (ROS, Python, C++) which we provide source to, but they're not on GitHub at the moment. Could you send me an email at sean.kelly@ifm.com?

**Comment by DUANlaoda** [comment]
Could you send me the Python or C++ source of Pallet Detection System (PDS) , duanfxld@gmail.com , thanks

**Comment by graugans** [comment]
@DUANlaoda please get in touch with @GarrettPlace

**Comment by GarrettPlace** [comment]
@DUANlaoda - you can reach me at garrett.place@ifm.com

**Comment by robologics1** [comment]
I would like to get source of Pallet Detection System, tlg.kayin@gmail.com , thanks

**Comment by graugans** [comment]
> I would like to get source of Pallet Detection System, [tlg.kayin@gmail.com](mailto:tlg.kayin@gmail.com) , thanks

As stated by Sean the Solution itself is closed source, the interface is available please reach out to Garrett his contact is available in 
 the comment https://github.com/ifm/ifm3d/issues/228#issuecomment-895175296
