### ISSUE TITLE
03D303 connection issues

### ISSUE THREAD

**Issue by Wanru-He** [ifm/ifm3d#233]
Hi there. I cannot connect my camera to my ubuntu 20.04 system when typing "ifm3d ls" into command prompt. It shows "ifm3d error: -100001 Lib: XMLRPC Timeout - can you `ping' the sensor?"
I have tried to ping the camera ip but it shows nothing beyond "PING 192.168.0.69 (192.168.0.69) 56(84) bytes of data.". I also tried finding the camera on angry ip scan, but the host seems to be dead. Is there a way I can resolve this? Thanks.

**Comment by Wanru-He** [comment]
I could connect to the ifm vision assistant on windows, but i cannot connect to the sdk.

**Comment by graugans** [comment]
Hey @Wanru-He have you already checked this troubleshooting guide: https://github.com/ifm/ifm3d/blob/master/doc/troubleshoot.md

**Comment by Wanru-He** [comment]
> Hey @Wanru-He have you already checked this troubleshooting guide: https://github.com/ifm/ifm3d/blob/master/doc/troubleshoot.md

Yeah, I have tried the methods on the guide, but there is still no information shown after I ping the camera besides the above message.

**Comment by graugans** [comment]
You are sure that both your Linux box and the camera are on the same IP network? You may experience issues with your host set-up to DHCP and you have set-up a point to point connection with the camera.

**Comment by Wanru-He** [comment]
Hi, I have manually reset the ip for the camera on the windows visual application. I can connect to my linux system now with my new ip address. Thanks for the help.

**Comment by zener90818** [comment]
@Wanru-He , I meet the same error, can you help me? https://github.com/ifm/ifm3d/issues/241
