### ISSUE TITLE
how to set the resolution to 352x264, the camera is O3D303

### ISSUE THREAD

**Issue by zener90818** [ifm/ifm3d#236]
the default pixel resolution is 176x132, how to get the resolution format up to 352x264. the code is shown below：
auto cam = ifm3d::Camera::MakeShared(New_ip);
auto fg = std::make_shared<ifm3d::FrameGrabber>(cam, (ifm3d::IMG_AMP | ifm3d::IMG_RDIS | ifm3d::IMG_CART));
auto img = std::make_shared<ifm3d::ImageBuffer>();

**Comment by graugans** [comment]
Hey @zener90818 please take a look at this comment: https://github.com/ifm/ifm3d/issues/145#issuecomment-492686044
