### ISSUE TITLE
Integration with cppcheck

### ISSUE THREAD

**Issue by theseankelly** [ifm/ifm3d#248]
This will consist of a few steps:

- [ ] 1. Run cppcheck on the ifm3d codebase
- [ ] 2. Identify and fix any real issues
- [ ] 3. Tune cppcheck to ignore issues we won't be fixing
- [ ] 4. Integrate into CMake
- [ ] 5. Include checks in CI

**Comment by graugans** [comment]
With cppchek take care to use a mor modern release than the one included in Ubuntu 18.04. Hm, maybe there is a snapped version.....
