### ISSUE TITLE
how get data from camera o3d303

### ISSUE THREAD

**Issue by PHILCHEN666** [ifm/ifm3d#271]
can i get camera data via some command in the linux temirnal.could you offer some Instruction manual?thank you very much

**Comment by graugans** [comment]
Hey @PHILCHEN666  sorry for the late reply. Currently we do not provide a out of the box command line tool to access the image data. But you can easily create one by your own. As a starter you can use This example code: https://github.com/ifm/ifm3d-examples/blob/master/file_io/
