### ISSUE TITLE
connect to halcon

### ISSUE THREAD

**Issue by PHILCHEN666** [ifm/ifm3d#277]
if i want connect the camera(O3D3xx) to halcon software in the computer ,what should i do.

**Comment by graugans** [comment]
Hey @PHILCHEN666 ,

there is a halcon driver available for the O3D3xx: https://www.mvtec.com/products/interfaces/documentation/view/65-3d-camera-12-mvtecdoc-o3d3xx/ In case of any question related to this driver please get in touch with our [support team](mailto:support.sy@ifm.com)
