### ISSUE TITLE
hAcqO3D3xx.dll or hAcqO3D3xxxl.dll

### ISSUE THREAD

**Issue by PHILCHEN666** [ifm/ifm3d#278]
how can i get the file of dll(hAcqO3D3xx.dll or hAcqO3D3xxxl.dll),when i use open_framegrabber in the halcon,Error happen cause of can't loadLibrary of hAcqO3D3xx.dll or hAcqO3D3xxxl.dl

**Comment by graugans** [comment]
Hey @PHILCHEN666 please get in touch with the support team mentioned in #277
