### ISSUE TITLE
provide windows binary releases

### ISSUE THREAD

**Issue by cwiede** [ifm/ifm3d#288]
**Is your feature request related to a problem? Please describe.**
There are binary releases for linux, but not for windows. Requesting our customers to compile the library themselfs on windows is a big hurdle.

**Describe the solution you'd like**
Please provide binary releases also for windows as assets attached to releases.

**Comment by tomatac** [comment]
It would be great to have binaries for windows. At least for major versions.
It takes some time to setup the environment to compile from source and it can be difficult for somebody with no C++ programming experience.

**Comment by graugans** [comment]
Hey @tomatac, there are Windows builds available here: https://github.com/ifm/ifm3d/actions/workflows/windows.yml

In case of any questions or comments please reach out to @inbangsa
