### ISSUE TITLE
Camera network configuration is self - negotiated or mandatory 100MB?

### ISSUE THREAD

**Issue by yuefanhao** [ifm/ifm3d#293]

**Comment by yuefanhao** [comment]
@graugans The MTU value will effect the performance of transmission delay ？

**Comment by yuefanhao** [comment]
@graugans Hi，I have question  about the O3D303 Camera send data in 1500bit chunk？

**Comment by graugans** [comment]
To the title of your question, it is auto negotiated and the we have not changed the default MTU which is 1500

**Comment by yuefanhao** [comment]
thank you.

**Comment by yuefanhao** [comment]
solved.
