### ISSUE TITLE
As the detection depth changes, can I know what the theoretical horizontal distance in reality is for every two pixels, assuming both pixels are in the same plane and parallel to the camera plane?

### ISSUE THREAD

**Issue by yuefanhao** [ifm/ifm3d#295]

**Comment by graugans** [comment]
I guess what you are looking for is the [Euclidean Distance](https://en.wikipedia.org/wiki/Euclidean_distance#Higher_dimensions) To calculate this you can use the cartesian coordinates XYZ for the two pixels you want to calculate the distance for.

**Comment by yuefanhao** [comment]
Shouldn't this have something to do with pixel density? If I want to know the distance between A and B, do I need to know the density of the light emitted by the camera?I'm sorry I didn't quite understand this.
![Screenshot from 2021-02-05 17-27-41](https://user-images.githubusercontent.com/35680714/107016136-8b253380-67d8-11eb-8ced-10f70e246b24.png)

**Comment by graugans** [comment]
By providing the Cartesian coordinates we have taken the optical model of the camera into account. This already contains the pixel density in my opinion. The only thing to consider is that a pixel is a square on the "Wall" which grows with the distance between the Wall and the camera. But @GreNait can provide more details and I guess even some graphics on this topic
