### ISSUE TITLE
How do I configure the camera with code?

### ISSUE THREAD

**Issue by yuefanhao** [ifm/ifm3d#296]
When I configure the camera with the following code：
![Screenshot from 2021-02-07 10-08-04](https://user-images.githubusercontent.com/35680714/107134388-9ab59100-692c-11eb-9ad9-725b1b2f912b.png)
There was an error：
![Screenshot from 2021-02-07 10-07-38](https://user-images.githubusercontent.com/35680714/107134402-ad2fca80-692c-11eb-8283-9cda19b153e2.png)

**Comment by lola-masson** [comment]
Hi @yuefanhao !
Which camera are you using? O3X, O3D?
Could you provide the full error message? Is there a specific line where the configuration fails or does it fail for every parameter?

**Comment by yuefanhao** [comment]
I'm using an O3D camera. The screenshot above is all the error messages. There is no specified line parameter configuration error. @lola-masson
