### ISSUE TITLE
Do the automatic exposure mode and TemporalFilter only work when the camera is in continuous mode? And does FlyingPixelEraser imprecise edge information?At the same time, it can reduce the impact of materials on depth information. Right?

### ISSUE THREAD

**Issue by yuefanhao** [ifm/ifm3d#297]

**Comment by lola-masson** [comment]
Auto exposure and Temporal filters both should work in continuous mode. You can test it quickly by configuring your camera through the CLI or the Vision Assistant.
The flying pixel eraser has an impact on edge detection: flying pixels are pixels that "land" partially on the edge on the object and partially on the background, leading to mixed measurement (the pixel ends up somewhere between the object and the background). A part of the object's edge is erased with the flying pixel eraser, however the part that is removed is invalid in the first place.
The flying pixel eraser should not have an impact on the depth measurement. The impact of different materials can be mitigated by changing the exposure time or using filters.

**Comment by yuefanhao** [comment]
Thank you.
