### ISSUE TITLE
How to calculate the minimum object size that can be detected at a given detection distance? For example, what is the actual horizontal distance between each pixel at a given detection distance?

### ISSUE THREAD

**Issue by yuefanhao** [ifm/ifm3d#301]

**Comment by MattVoge** [comment]
Hi Yuefanhao,
Maybe you could use resolution + viewing angle to calculate the distance. E.g. viewing angle is 45°, resolution is let's say 100px. So delta is 0.45° per pixel. Now you can use trigonometry to calc the distance between pixels at a given distance. However, you should also pay attention to potential rectification of the image which may need you to adapt trigonometry approach.
