### ISSUE TITLE
Slow connection

### ISSUE THREAD

**Issue by alexsve83** [ifm/ifm3d#306]
I've got 6 IFM cam directly connected  (6 Network interface ) to the PC, I've seen in the code that there's 3sec timeout in the connection, and I expect 18sec to connect all the cameras, but it takes at least 1minute.
Is this normal? Is there something to speed up the connection?

**Comment by graugans** [comment]
Hey @alexsve83 , can you please provide more details. What do you mean by connection? Maybe some sample code can help to better understand your problem.

Typically the boot time of a camera is ~30 seconds, a connection typically takes less than a second. When you configure the device this may take longer, but still below one minute. If you do not configure the camera and only grab images from the camera it is only a matter of your trigger configuration when the data comes.

The easiest way to figure all this out is to receive a dum of the configuration of each camera:

```
ifm3d dump > camera-<Last three octets of the camera MAC address>.json 
```
