### ISSUE TITLE
 How to get O3D303 camera temperature by ifm3d lib?

### ISSUE THREAD

**Issue by haoyuefan** [ifm/ifm3d#324]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior. For example:

**Expected behavior**

**Output/Screenshots**
If applicable, add console output and/or screenshots to help explain your problem.

**Minimal Working Example**
If applicable/possible, please provide a [minimal working example](https://stackoverflow.com/help/minimal-reproducible-example) which demonstrates the problem and can be run standalone.

```
#include <iostream>
int main()
{
  std::cout << "Hello World!" << std::endl;
  return 0;
}
```

**Configuration/Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04, Windows 10]
 -  ifm3d version: [e.g. 0.14.0]
 - using ROS: [yes/no]

**Camera Configuration**
Please include the output of `ifm3d dump`

**Additional context**

**Comment by inbangsa** [comment]
@haoyuefan following are the ways to obtain the device temperature (illumination temperature) with ifm3d lib and tool

* From command line you can use ```ifm3d dump``` command
```Terminal
ifm3d dump | jq '.ifm3d.Device.TemperatureIllu'
```
* You can do the same in code with following code snippet
```C++
auto cam = ifm3d::Camera::MakeShared();
std::cout << cam->ToJSON()["ifm3d"]["Device"]["TemperatureIllu"];
```
* You can also grab the temperature value along with other data/images by adding ```ifm3d::ILLU_TEMP``` to the framegrabber schema-mask parameter. This is the a good way to monitor the camera temperature.  following is the code snippet
 
```C++
auto cam = ifm3d::Camera::MakeShared(); 
ifm3d::ImageBuffer::Ptr img = std::make_shared<ifm3d::ImageBuffer>();
ifm3d::FrameGrabber::Ptr fg = std::make_shared<ifm3d::FrameGrabber>( cam, ifm3d::DEFAULT_SCHEMA_MASK|ifm3d::ILLU_TEMP);

  if (!fg->WaitForFrame(img.get(), 1000))
    {
      std::cerr << "Timeout waiting for camera!" << std::endl;
      return -1;
    }
 /* grab the illumination temperature */
  std::cout <<  img->IlluTemp();

```
