### ISSUE TITLE
The internal parameter about the O3D303 camera

### ISSUE THREAD

**Issue by PHILCHEN666** [ifm/ifm3d#327]
hello ifm engineer,i'm a student in china,recently,i was studying a new calibration method for TOF camera,i use this new algorithm to get the internal parameter of O3D303 camera,but i want to compare the parameter getted by my method with your company real parameter,unfortunately, the ifm company in china tell me,the Headquarters company in German cannot provide the internal parameter about the O3D303 camera, i dont know why,Germany is a country that advocates advanced technology. In [1] (An Incremental Procedure for the Lateral Calibration of a Time-of-Flight Camera by One Image of a Flat Surface) this paper mentioned that the depth camera of IFM.i believe the internal parameter of the depth camera also can release to china consumers, but the ifm company in China does not provide it to consumers. I am not clear about the reason, but I hope IFM can provide the internal reference of this O3D303 camera in the respect of Chinese consumers. I only use it for research work. Thank you sincerely for your understanding.

**Comment by SLAMDUNK4ROT** [comment]
兄弟，ifm o3d 你是怎么标定出内参的，我采出来数据集得到的Amplitude_Image，但质量并不高，棋盘格的内交点很多都不是真实的。 我看你求出来了，请问下你是用什么方法，谢谢

**Comment by graugans** [comment]
Hey @SLAMDUNK4ROT, I ran your comment through Google translate. 

> Brother, ifm o3d, how did you calibrate the internal parameters? The Amplitude_Image I got from the data set, but the quality is not high, and many of the internal intersections of the checkerboard are not real. I think you have found it out, what method do you use, thank you

There is no calibration needed for the device. They are calibrated during production. Please check the two examples for more details:

- [image_rectification](https://github.com/ifm/ifm3d-examples/tree/master/image_rectification/python)
- [intrinsics_to_cartesian](https://github.com/ifm/ifm3d-examples/tree/master/intrinsics_to_cartesian/python)

**Comment by SLAMDUNK4ROT** [comment]
Dear Christian
Thanks your promptly relpy, the reason I wanna get the internal params is that I use both RGB camera and tof for asscociation to get 2d image information and depth data as same as rgb-d camera. So in order to precision, I have to calculate the' T 'matrix (R t) between RGB and TOF by the internal params of TOF( the internal params of RGB I have got). Could you help me to get the internal params of imf or improve the quality of images I get from ifm.

Many thanks
SL4ROT

**Comment by SLAMDUNK4ROT** [comment]
Dear Christian
Thanks, btw du u know how to get the Grarscale_image?  I have found this Mat in ifmo3d_driver.cpp, is it right? 
Many thanks

**Comment by graugans** [comment]
Hey @SLAMDUNK4ROT it depends what you refer to when talking about Grayscale image. If you consider the Amplitude image to be the grayscale image than you can query it with [IMG_AMP](https://github.com/ifm/ifm3d/blob/master/doc/schema.md) this contains the information about the reflectivity of your scene based on the active light source we do use in our TOF cameras. When you are interested in a grayscale image which contains the reflectivity of the scene without the camera light source active. This is currently not supported.

**Comment by SLAMDUNK4ROT** [comment]
Dear Christian 
Yeah, that's what I want that the Grayscale Image instead of Amplitude Image as input data for caliberation. I will try to call it in cpp later and many thanks for your help.

Marry Christmas
SD4R

**Comment by SLAMDUNK4ROT** [comment]
Dear Christian
I have used the code you recommended from https://github.com/ifm/ifm3d/blob/master/doc/schema.md , but it was no value in " img -> GrayImage()". I have set the function 
**auto fg = std::make_shared<ifm3d::FrameGrabber>(cam,ifm3d::IMG_RDIS|ifm3d::IMG_AMP|ifm3d::IMG_GRAY);** 
Even , **auto fg = std::make_shared<ifm3d::FrameGrabber>(cam,mask);** I set "mask =67(1+2+64)", but it was still no value.

**Comment by lola-masson** [comment]
@SLAMDUNK4ROT as @graugans mentioned, grayscale image is not currently supported.

**Comment by puyiwen** [comment]
> 亲爱的 Christian 感谢您及时回复，我想获取内部参数的原因是我使用 RGB 相机和 tof 进行关联以获得与 rgb-d 相机相同的 2d 图像信息和深度数据。所以为了精确，我必须通过TOF的内部参数（我得到的RGB的内部参数）来计算RGB和TOF之间的'T'矩阵（R t）。你能帮我获取 imf 的内部参数或提高我从 ifm 获得的图像质量吗？
> 
> 非常感谢 SL4ROT

Hi, how do you get the extrinsic metric from the TOF and RGB camera intrinsic metric? I also do that for aligning the TOF and RGB , but I am a new, could you help me about that? My WeChat is puanni0123, and my QQ is 291931809. Thank you very much!

**Comment by lola-masson** [comment]
Hi @puyiwen,
Are you using an O3D303 or are you using the O3R platform (OVP800 + O3R22x)?
For the O3R, we have an example that explains [how to align the 2D and 3D images here](https://ifm3d.com/o3r-utilities/registration2d3d/README.html), maybe this can get you started.

**Comment by YBachmann** [comment]
> Hi [@puyiwen](https://github.com/puyiwen), Are you using an O3D303 or are you using the O3R platform (OVP800 + O3R22x)? For the O3R, we have an example that explains [how to align the 2D and 3D images here](https://ifm3d.com/o3r-utilities/registration2d3d/README.html), maybe this can get you started.

Hi @lola-masson , 
the link [how to align the 2D and 3D images here](https://ifm3d.com/o3r-utilities/registration2d3d/README.html) does not work anymore. 
Could you point me to a current working example?

**Comment by lola-masson** [comment]
@YBachmann for the O3R, the 2D/3D registration example can be found here: https://github.com/ifm/ifm3d-examples/blob/main/ovp8xx/python/ovp8xxexamples/toolbox/registration_2d_3d.py
