### ISSUE TITLE
conflicted with other rpc tool such as xmlrpc/rcf on TX2(aarch64) platform 

### ISSUE THREAD

**Issue by cadaeb** [ifm/ifm3d#329]
conflicted with other rpc tool such as xmlrpc/rcf on TX2(aarch64) platform 

**To Reproduce**
Choose nvidia TX2 platform

1.  Add a rpc lib such as "RCF" in the same program and create a thread to build a TCPEndpoint such as follows:
static RCF::RcfInit rcfInit;
std::string networkInterface = "192.168.0.66";
int port = 50001;

// Start a TCP server, and expose DemoService.
DemoService demoService;
static RCF::RcfServer server( RCF::UdpEndpoint(networkInterface, port) );
server.bind<I_DemoService>(demoService);
server.start();  

2.  Initilize IFM3d in another thread such as follows:
std::string port_name;
port_name = "192.168.0.69";
m_Camera = std::make_shared<ifm3d::Camera>(port_name);
m_FrameGrabber = std::make_shared<ifm3d::FrameGrabber>(m_Camera);
m_ImageBuffer = std::make_shared<ifm3d::ImageBuffer>();

3. No matter whether grabbing the IFM frame, the program willl be dumpped  with a gdb result as follows:

```
0x0000005555994f94 in void asio::detail::op_queue_access::next<asio::detail::task_io_service_operation, asio::detail::task_io_service_operation>(asio::detail::task_io_service_operation*&, asio::detail::task_io_service_operation*) ()
(gdb) bt
#0  0x0000005555994f94 in void asio::detail::op_queue_access::next<asio::detail::task_io_service_operation, asio::detail::task_io_service_operation>(asio::detail::task_io_service_operation*&, asio::detail::task_io_service_operation*) ()
#1  0x000000555596bca8 in asio::detail::op_queue<asio::detail::task_io_service_operation>::push(asio::detail::task_io_service_operation*) ()
#2  0x000000555595b880 in asio::detail::task_io_service::post_immediate_completion(asio::detail::task_io_service_operation*, bool) ()
#3  0x0000005555959f64 in asio::detail::epoll_reactor::start_op(int, int, asio::detail::epoll_reactor::descriptor_state*&, asio::detail::reactor_op*, bool, bool) ()
#4  0x000000555595e588 in asio::detail::reactive_socket_service_base::start_op(asio::detail::reactive_socket_service_base::base_implementation_type&, int, asio::detail::reactor_op*, bool, bool, bool) ()
#5  0x0000007fb17a2128 in  () at /usr/local/lib/libifm3d_framegrabber.so.0.20.0
#6  0x0000007fb17a2304 in  () at /usr/local/lib/libifm3d_framegrabber.so.0.20.0
#7  0x0000007fb17a265c in  () at /usr/local/lib/libifm3d_framegrabber.so.0.20.0
```
It will in a same case when I use a simple XMLRPC server. And I guess all these RPC tools may use same fundmetal boost lib where something unexcecpted happens.

I struggled to use static or shared linked lib and both failed .

**Comment by graugans** [comment]
@cadaeb and @inbangsa  It looks like there is also a similar issue within [Fast-DDS](https://github.com/eProsima/Fast-DDS/issues/1484)
