### ISSUE TITLE
Cannot connect to O3R Camera using ifm3d library

### ISSUE THREAD

**Issue by mehranq** [ifm/ifm3d#331]
Hello. I am trying to test out the O3R camera using the C++ example provided here: https://ifm.github.io/ifm3d-docs/examples/o3r/configuration/configuration.html. I am using the Windows platform and built the ifm3d library from source using your "Building ifm3d from source on Windows" guide without the PCL dependency and using the o3r/main-next branch. 

The camera is connected to my pc and I am able to ping it successfully at **192.168.0.69** through command prompt on windows.

However when I try to connect to the camera using the example program in the link above it still fails to connect to the camera and I get the an exception when it gets to the line `json conf = cam->Get();`. See the first screenshot below.

Interestingly, if i explicitly define the ip address and port no using `auto cam = std::make_shared<ifm3d::O3RCamera>("192.168.0.69", ifm3d::DEFAULT_XMLRPC_PORT);` in the cam object constructor it throws a different exception right there at the camera object declaration line and the exception source is in a file called **xutility**. See the second screenshot below. It does not seem to matter whether the above explicit ip address is a valid one or not. I tried passing an invalid ip address like **192.168.0.50** and it would still throw the same exception in **xutility**. 

Hope you can advise on what the issue might be. The camera does respond successfully when pinging it through the command prompt but it just does not seem to connect through the example C++ program.

![error without explicitly specifying ip address of camera](https://user-images.githubusercontent.com/25999707/140951321-d0e6d4c4-2d9f-43a2-933d-b0e21677d542.png)
![error when explicitly specifying ip address of camera](https://user-images.githubusercontent.com/25999707/140951330-5031e180-c1f9-4852-934b-e809931f3a7e.png)

**Comment by graugans** [comment]
Hey @mehranq ,
what Visual Studio version are you using?

**Comment by inbangsa** [comment]
@mehranq  are you building example in Debug mode ? 
can you try building example in Release mode,

by default ifm3d is build in release mode.

**Comment by mehranq** [comment]
> Hey @mehranq , what Visual Studio version are you using?

I am using Visual Studio 2019.

**Comment by mehranq** [comment]
> @mehranq are you building example in Debug mode ? can you try building example in Release mode,
> 
> by default ifm3d is build in release mode.

Yes. I am building it debug mode. I'll try building the example in release mode. Thank you for the suggestion.

**Comment by mehranq** [comment]
> @mehranq are you building example in Debug mode ? can you try building example in Release mode,
> 
> by default ifm3d is build in release mode.

I just tried building in release mode. I am still getting an exception on line  `json conf = cam->Get();`. However the exception type changed to `ifm3d::error_t` whereas previously when running in debug mode, the exception type was `std::bad_array_new_length`

Also, I don't get the exception in **xutility** anymore when explicitly specifying the ip address and port  for the camera.  Instead the code does continue running and throws the same above `ifm3d::error_t` exception on the line `json conf = cam->Get();`

So now, I get the same exception regardless of whether I explicitly specify the ip address and port now in camera constructor or not.  Here is a screenshot of the exception:

![exception on release build](https://user-images.githubusercontent.com/25999707/140970626-e1e530a9-11f1-41fb-beb8-4f66a7f5ba65.png)

**Comment by inbangsa** [comment]
@mehranq can you please provide dump of the device configuartion.

you need to do this with ifm3d tool which is installed in your PC while installing ifm3d. you will find this tool in ```<install prefix path>/bin```

getting the dump :

> ifm3d dump 

this will help us to understand the configuration of your device and firmware that you are using.

**Comment by mehranq** [comment]
I tried using ifm3d dump as instructed but that command throws an error like this

![ifm3d dump error](https://user-images.githubusercontent.com/25999707/140998040-84366c07-34ab-401d-bc9c-03b80b3ce71d.png)
:

When adding the try catch snippet above to the C++ example code, the error code seems to be the same as the one I get when trying to run ifm3d dump:

![error detail](https://user-images.githubusercontent.com/25999707/140998194-c8321d0d-05b7-4328-a0f2-4078b4fda950.png)

**Comment by desengph** [comment]
Hi @mehranq 
this sounds "suspiciously" similar to a mismatch of firmware and software versions to me. 

Can you please check that you are using a recent O3R VPU firmware version (version >= 0.13.11). The easiest way to check this is the use of our web front-end: `http://192.168.0.69/api/rpc/v1/com.ifm.efector/`. Copy and paste the `getSWVersion` command into the second box from the top, label method. Any other box stays doesn't need any user input for this command.

Also can you please double check that your power supply is capable of supplying the required 5 Amp at 24V.

**Comment by graugans** [comment]
Hi, @mehranq,

like @desengph mentioned you may have some old O3R firmware running. The easiest way to query the firmware version is pasting this line in the address bar of your browser:

```
http://192.168.0.69/api/rpc/v1/com.ifm.efector/?method=getSWVersion
```

The result looks like this:
```
Response
{ "error": null, "id": null, "result": { "IFM_Software": "0.14.0-242", "Linux": "Linux version 4.9.140-l4t-r32.4+gc35f5eb9d1d9 (oe-user@oe-host) ", "Main_Application": "0.16.0" } }
```
In your case there maybe an older FW version

**Comment by mehranq** [comment]
Hi @graugans @desengph
Here is the result of the api call that you suggested to check the firmware version:

![image](https://user-images.githubusercontent.com/25999707/141137045-d7336f75-0462-4958-b57c-8cc3368a6007.png)

It does look like the firmware version is old on my end. How should I go about updating the firmware?

Also, just to confirm, I am using the following power supply supplied by IFM. The output is rated at 3A 24V. Just FYI, we only have one camera connected to the VPU so I would assume it should be enough power:

![20211110_100906](https://user-images.githubusercontent.com/25999707/141139586-b73e5f1e-fc49-409d-b3ee-d27266e8b687.jpg)

**Comment by desengph** [comment]
Hi @mehranq 
I'm sorry to say but your firmware on the O3R camera is ancient. 
We will have to see if we can update your hardware without risking a software hardware incompatibility for early field test hardware.

@mehranq can you please send me a PM. We will have to discuss the details in private.

I'm sorry for the confusion earlier.

Best regard,
Philipp

**Comment by mehranq** [comment]
@desengph 
Sure. How do I get in touch with you privately?

**Comment by desengph** [comment]
@mehranq 
I just relalized that GitHub removed their direct messages service.
Can please send me an email philipp.senger<at>ifm.com

Otherwise let me know your email address so I can shoot you an email.

**Comment by mehranq** [comment]
@desengph 
I just shot you a quick email. Thanks.

**Comment by desengph** [comment]
Got it. 
I will collect the necessary information from my Canadian colleagues and answer you tomorrow.

**Comment by mehranq** [comment]
Great. Thank you.

**Comment by inbangsa** [comment]
@mehranq if your issue is resolved can you please close this.

**Comment by mehranq** [comment]
@inbangsa sure. Closing it now.
