### ISSUE TITLE
Unify indexes starting at 0 or 1 in the json dump

### ISSUE THREAD

**Issue by akaddoura** [ifm/ifm3d#343]
Minor pet peeve but I noticed the indexes in the json dump are not unified. The camera resolution index starts at 0 while the Active App and Trigger Mode indexes start at 1. 

This is for an O3D311 camera running ifm3d 0.20.0.

**Comment by graugans** [comment]
Hey @akaddoura , thanks for pointing this out. The app index zero is used internally and this is the reason why there is no index of `0`. The trigger mode is handled this way for backward compatibility. The rest of the indices are starting as usual with the index `0`.
