### ISSUE TITLE
Read-only file system error

### ISSUE THREAD

**Issue by robinbansal08** [ifm/ifm3d#346]
We are running our application over IFM O3D303 sensors, the application along with other processes also tries to renames local files. But sometimes we are facing error:  can't rename: Read-only file system. This issue is resolved after sensor reboot. Can you provide any suggestion about why this happening.

**Comment by lola-masson** [comment]
@robinbansal08 Could you give more information: firmware version? are you using ifm3d? what code are you trying to run that triggers the error? Is there anything else in the error message?
