### ISSUE TITLE
How to achieve an image / Point Cloud similar to the ones displayed in the Vision assistant

### ISSUE THREAD

**Issue by LarsBuck** [ifm/ifm3d#351]
Hello,

after experimenting with the python library I am now able to get the distance image, but it does not look as similar as presented in the Vision assistant. What preprocessing is needed to achieve such an image. We are currently using Opencv applyColormap method for visualisation.

![ifm3do3d300_dep](https://user-images.githubusercontent.com/35806798/157894866-7e8b967c-697a-4570-a6e4-15becb709c83.png)
 
In the Vision Assistant there are linear and logarithmic transformations added to image, which will probably lead to a better result. How can we use these in python. Do you have any information on that ? 

__________

Another question i have is how can i access the point cloud data with the python library. I've seen documentation about the .cloud() function but it is only available in c++. Is there a similar function in python to create a point cloud like in the Vision Assistant / PCL Viewer.

Thanks for your help.

**Comment by lola-masson** [comment]
Hi Lars,

The point cloud can be retrieved with the [xyz_image()](https://ifm3d.com/sphinx-doc/build/html/api/ifm3dpy.ImageBuffer.html#ifm3dpy.ImageBuffer.xyz_image) function in python. You can have a look at [this example](https://github.com/ifm/ifm3d/tree/o3r/main-next/examples/o3r/viewer), which is a python viewer implemented using openCV and open3D. 
What exactly are you trying to achieve with the display? Is it the contrast that is not sufficient?
