### ISSUE TITLE
Which ifm3d-version goes with which version of the O3R firmware?

### ISSUE THREAD

**Issue by j-friedl** [ifm/ifm3d#356]
It would be really great if you could provide a summary of the current O3R firmware version to ifm3d version compatibility. I've struggled to get the system running for quite a while now. The firmware currently running on my **OVP800** is **0.14.23-493**. Is there any stable and functioning version of ifm3d that works? The ones I tried (**0.20.***) all failed in multiple ways. I can ping the system on IP 192.168.0.69, however all the ifm3d command line functions fail (ifm3d error: stoi for ifm3d dump). My OS is **Ubuntu 20.04**.
Another strange thing is that "ifm3d dump" does work on the "ghcr.io/ifm/ifm3d:latest" docker image, however the other commands also fail.
I'm guessing that the firmware version is too new for this ifm3d release?

**Comment by lola-masson** [comment]
Hi @j-friedl,
You are right, we need to write a detailed compatibility matrix for all the different software and firmware packages. In the meantime, we recommend using tagged versions, the latest is [0.93.0](https://github.com/ifm/ifm3d/releases/tag/v0.93.0). Similarly, use the `stable` or `v0.93.0` docker container tag. 
You have the latest firmware version, 14.23, so you're good on that side.

**Comment by j-friedl** [comment]
Thanks for the fast response! As I'm not that familiar with CMake, how would the building process work if i use the compressed file? For me, if I unzip the folder, go into it, mkdir build and run "**cmake -DCMAKE_INSTALL_PREFIX=/usr ..**" I get following error message:

> -- Setting build type to 'RelWithDebInfo' as none was specified.
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> CMake Error at cmake/modules/GetVersionFromGitTag.cmake:59 (string):
>   string sub-command REGEX, mode MATCHALL needs at least 5 arguments total to
>   command.
> Call Stack (most recent call first):
>   CMakeLists.txt:13 (include)
> 
> 
> CMake Error at CMakeLists.txt:25 (project):
>   VERSION "NOTFOUND.NOTFOUND.NOTFOUND" format invalid.
> 
> 
> -- Configuring incomplete, errors occurred!
>

**Comment by lola-masson** [comment]
Sorry about that, this is indeed a bug in the build process using the zip. We are working on it, but in the meantime a way around is:
- Comment the lines 38 to 96 (included) and line 111 in the ifm3d/cmake/modules/GetVersionFromGitTag.cmake
- Create a document with the line below and save it as /ifm3d/VERSION.
VERSION file:
```
v0.93.0+2.e724b30*v0.93.0*0*93*0**2*e724b30
```

**Comment by himanshuak** [comment]
> Sorry about that, this is indeed a bug in the build process using the zip. We are working on it, but in the meantime a way around is:
> 
> * Comment the lines 38 to 96 (included) and line 111 in the ifm3d/cmake/modules/GetVersionFromGitTag.cmake
> * Create a document with the line below and save it as /ifm3d/VERSION.
>   VERSION file:
> 
> ```
> v0.93.0+2.e724b30*v0.93.0*0*93*0**2*e724b30
> ```

Hello, i am trying to build the ifm3d lib from source to use it for ifm3d ros. I followed the same steps to build, but the `cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_MODULE_OPENCV=ON -DBUILD_MODULE_PCICCLIENT=ON -DBUILD_MODULE_IMAGE=ON  ..` gave me the same error. My question is, What should be put in the VERSION file since im using the latest release `v1.1.0`?

**Comment by lola-masson** [comment]
Hi @himanshuak,
Our ros drivers are not yet compatible with the latest versions of ifm3d, 1.x.x. To use ROS with the O3R, you will need to use ifm3d 0.93.0.
Sorry for the inconvenience.

**Comment by himanshuak** [comment]
> v0.93.0+2.e724b30*v0.93.0*0*93*0**2*e724b30

Thankyou for the quick response. I was able to successfully build both ifm3d and ifm3d_ros. Will be soon trying out different robotics applications using your sensor.

**Comment by lola-masson** [comment]
Great, do not hesitate to reach out if you have additional questions.
