### ISSUE TITLE
ImportError: cannot import name 'O3RCamera' from 'ifm3dpy'

### ISSUE THREAD

**Issue by plraimb** [ifm/ifm3d#367]
Hello, 
I have just started to work with O3D, using python.
And I have a problem when I want to do an import like 'from ifm3dpy import O3RCamera', I have the following error message "ImportError: cannot import name 'O3RCamera' from 'ifm3dpy'"

Have you ever encountered this type of problem? Do you have a solution or an idea where it could come from?

**Comment by lola-masson** [comment]
Hi @plraimb,

Are you using the **O3D** or the **O3R**?
- If you are using the O3D, you should use ifm3d 0.20.x, as we the newest versions of ifm3d are not yet fully compatible with the O3D. With ifm3d 0.20.x, the python bindings need to be built from source or installed with the debs: https://github.com/ifm/ifm3d/releases/tag/v0.20.3
- If you are using the O3R, then you should follow the instructions [here](https://ifm3d.com/sphinx-doc/build/html/index.html).

The import error you mentions above makes me think of a version issue, so please let us know what your setup is.

Thanks.
