### ISSUE TITLE
Compiling from Source for ROS Noetic on Ubuntu -- stlimage-tests error

### ISSUE THREAD

**Issue by samialperen** [ifm/ifm3d#380]
**Describe the bug**
I am trying to follow the build from source document [here](https://github.com/ifm/ifm3d/blob/v0.20.3/doc/source_build.md). However, for either v0.91.0 or v.0.93.0, I am getting the error in the screenshot about **ifm3d-stlimage-image-tests**. 

My goal is to make ROS wrapper work for ROS noetic. Can someone please help me out? Thank you! :) 

![image](https://user-images.githubusercontent.com/30050658/212139001-19cc1e0e-285e-4696-96a6-6b2fefd8dd57.png)

**Comment by lola-masson** [comment]
Hi @samialperen,
The tests are not intended to be ran when simply building ifm3d for "normal" use. They expect a specific hardware configuration that you might not have. You should be able to ignore the failed tests and continue with the build.

It also appears that you are following documentation for ifm3d version 0.20.3. For version 0.93.0, you should follow the instructions in the corresponding branch: https://github.com/ifm/ifm3d/blob/v0.93.0/doc/sphinx/content/source_build.md.

I would recommend starting fresh building ifm3d with the instructions above. Make sure you cleanup previous builds (is there anything left in /usr/lib/cmake/ifm3d*, or other directories? If yes delete them.)
