### ISSUE TITLE
How to run the ifm-O3X120 camera ros driver in a docker container

### ISSUE THREAD

**Issue by Lyk77** [ifm/ifm3d#399]
Our AGV industrial computer uses Ubuntu18.04 system, on which ros image is used to create docker container. We need to put the ros driver of ifm-O3X120 camera into the container to run, may I ask how to execute it

**Comment by dekhanra** [comment]
Hi @Lyk77, the last ifm3d version supporting O3X1xx cameras is v0.20.3. Please refer to another repository that maintains ROS drivers for ifm cameras at https://github.com/ifm/ifm3d-ros . I beleive this issue thread may be helpful https://github.com/ifm/ifm3d-ros/issues/74 in your case.
