### ISSUE TITLE
Problem with glog

### ISSUE THREAD

**Issue by pfrydlewicz** [ifm/ifm3d#40]
Hi,
when compiling on Ubuntu 16.04 I get following error message once calling ifm3d.
Anyone has an idea what might be wrong?
I compiled glog manually.

ERROR: something wrong with flag 'logtostderr' in file '/home/paul/Downloads/glog-0.3.5/src/logging.cc'.  One possibility: file '/home/paul/Downloads/glog-0.3.5/src/logging.cc' is being linked both statically and dynamically into this executable.

**Comment by graugans** [comment]
@pfrydlewicz there is no need to compile glog on ubuntu. You can install it directly by ``apt``.

```
apt-get update && apt-get -y upgrade
# Required Packages for the Host Development System
apt-get install -y libboost-all-dev \
    git \
    jq \
    libcurl4-openssl-dev \
    iputils-ping \
    bash \
    bash-completion \
    libgtest-dev \
    libgoogle-glog-dev \
    libxmlrpc-c++8-dev \
    libopencv-dev \
    libpcl-dev \
    libproj-dev \
    build-essential \
    coreutils \
    cmake
```

Like I do in my [docker image for ifm3d](https://github.com/graugans/docker_images/blob/master/ifm3d/Dockerfile)
