### ISSUE TITLE
O3D303 measure dimensions on Ubuntu 22

### ISSUE THREAD

**Issue by SystemDiagnosticss** [ifm/ifm3d#413]
Hi. I have IFM O3D303 camera. I need to measure dimensions of different boxes on a conveyor.  In my case, I want to connect it to Raspberry Pi 4 under Ubuntu 22. I would be satisfied with a ready-to-use solution from Wizard "Dimensioning of rectangular objects" but O3D303 does not support it (it works only on O3D300, O3D302).  And I no have idea how I can run it under Ubuntu. 

So my question is - How I can measure dimensions of boxes using IFM O3D303 under Ubuntu?

**Comment by lola-masson** [comment]
Hi @SystemDiagnosticss,

This feature is only available for the O3D302 (the sensor, not the camera). And the algorithms on board the sensor are only available through the Vision Assistant. For Ubuntu and the O3R303, you would need to implement the algorithm yourself.

**Comment by SystemDiagnosticss** [comment]
Thanks for your answer @lola-masson, maybe you know about some source code examples for it on Python or C++ ? Maybe someone has already done this?

**Comment by lola-masson** [comment]
We don't have any examples ready for object dimensioning. Maybe have a look at [Open3D](http://www.open3d.org/docs/release/index.html) has something that you could use.

**Comment by SystemDiagnosticss** [comment]
And last questions. Is it possible to run something like visionassistance.dll and run it without x-screen and use maybe some API to send data from o3d302 with pre-installed "Dimensioning of rectangular objects" via Ethernet connection to my app?

**Comment by graugans** [comment]
Since the O3D302 is using the same communication mechanism like the O3D303 this shall be possible with the ifm3d. In case you have a configured Dimensioning app it is just a matter of configuring the result data stream and also to interpret that stream. You can check if the [JSON_MODEL](https://github.com/ifm/ifm3d/commit/2e8dff4fd7ef7bb7bbbf372775fbbd7f84599e00) contains the required result data.

**Comment by SystemDiagnosticss** [comment]
@graugans Thanks I try
