### ISSUE TITLE
[ifm3d 1.3.3] O3R 2D intrinsic calibration values access

### ISSUE THREAD

**Issue by desengph** [ifm/ifm3d#414]
When trying to access the extrinsic / intrinsic calibration values of a 2D stream, I get the following log messages.

These are logs and not explicitly raised as exceptions to ensure backward compatibility with existing code.

``
2023-07-20 16:07:27 ERROR [/builds/syntron/support/csr/ifm3d/ifm3d/modules/framegrabber/src/libifm3d_framegrabber/default_organizer.cpp:60] No meta chunk found!
2023-07-20 16:07:27 WARN [/builds/syntron/support/csr/ifm3d/ifm3d/modules/framegrabber/src/libifm3d_framegrabber/frame_grabber_impl.hpp:632] Bad image: std::exception**Describe the bug**
``

**Configuration/Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 -  ifm3d version: e.g. 1.3.3
 - using ROS: no

**Fix**
This is a known bug when accessing the ifm3d helper method Extrinsic and Intrinsic of a RGB stream.
These helper methods will be fixed in future versions.

**Workaround**
Use the RGB_INFO chunk and deserialize via its respective deserializer module:
https://api.ifm3d.com/stable/_autosummary/ifm3dpy.deserialize.RGBInfoV1.html#ifm3dpy.deserialize.RGBInfoV1.intrinsic_calibration

**Comment by BigBoot** [comment]
The deserialize module is the way to access structured data going forward, the helper code for the TOFInfo chunks will be kept for backwards compatibility, but no new helper code will be added.
