### ISSUE TITLE
O3D303 rotation matrix

### ISSUE THREAD

**Issue by yasin333** [ifm/ifm3d#425]
I use ifm O3D303 tof camera.And i rotate camera around it's x  axis.How can i find real z(depth) value?Should i use rotation matrix formula or intrinsic calibration code?

**Comment by dekhanra** [comment]
Hi   @yasin333 , which ifm3d version you are using ?

**Comment by yasin333** [comment]
> Hi @yasin333 , which ifm3d version you are using ?

I use ifm3dpy python library and it’s pip version 0.93.0. I dont’t use ifm vision studio.

**Comment by dekhanra** [comment]
hI @yasin333, The latest ifm3d version has a XYZ image availability and you can use this buffer to get the depth value. Regarding the v0.93.0 please look at this changelog https://github.com/ifm/ifm3d/blob/main/ChangeLog.md#changed-4 to keep the old behaviour of Camera.
