### ISSUE TITLE
missing poky-glibc-i686-vantage-image-armv7ahf-vfp-neon-toolchain-qte-1.8.1.sh file for cross_compiling

### ISSUE THREAD

**Issue by ccqedq** [ifm/ifm3d#426]
can't find poky-glibc-i686-vantage-image-armv7ahf-vfp-neon-toolchain-qte-1.8.1.sh for cross_compiling, how can I get it?

**Comment by lola-masson** [comment]
Hi @ccqedq, could you give us more details about what you are trying to do? Which version of ifm3d, are you creating a docker container, what is the destination architecture + OS you are compiling for, what is the error message you are seeing, etc. Thanks.

**Comment by ccqedq** [comment]
I want to compile code for arm architecture using x86 LINUX system, and found some tutorial in ifm3d/doc/cross_compiling.md，which using poky-glibc-i686-vantage-image-armv7ahf-vfp-neon-toolchain-qte-1.8.1.sh to perform some operation. but I can't find it in the project.
![图片](https://github.com/ifm/ifm3d/assets/37147472/ab611468-cc8a-4790-800f-1399cb20fda2)

**Comment by ccqedq** [comment]
I use ifm3d 1.4.3 and compile the code by source instead of docker

**Comment by graugans** [comment]
What platform you want to run ifm3d on? Maybe that specific Toolchain is not the one you are looking for?
