### ISSUE TITLE
A coredump exception occurred in the libifm3d_camera.so.0.17.0 library

### ISSUE THREAD

**Issue by jixiangwangzi** [ifm/ifm3d#432]
**Configuration/Environment (please complete the following information):**
 - OS: [Ubuntu 18.04]
 -  ifm3d version: [e.g. 0.17.0]
 - using ROS: /no]

![image](https://github.com/ifm/ifm3d/assets/44867627/09252797-b14d-4446-b335-ca3a4bbb62d3)

**Comment by graugans** [comment]
Hej @jixiangwangzi is there a minimal example to reproduce this? Otherwise it is quite hard to reproduce this behaviour.
