### ISSUE TITLE
Provide a library that does not perform glog initialization and glog environment variable configuration

### ISSUE THREAD

**Issue by Bwolf89** [ifm/ifm3d#436]
Our company uses your company's camera model O3D303CN;

Our company has also adopted Glog as the logging system. We found that there was a conflict with your company's Glog initialization during the initialization and configuration of Glog logs, which resulted in unexpected logging behavior

**Comment by lola-masson** [comment]
Hi @Bwolf89,
The dependency to Glog has been removed in version 1.3.2. You can try updating your code to the latest ifm3d version (1.4.3), and you will be able to use the customer logging functionality. Note that support for O3D is still experimental in this version of ifm3d.
