### ISSUE TITLE
ifm3d O3DP03 camera data getting problem

### ISSUE THREAD

**Issue by Ken-Jia** [ifm/ifm3d#446]
**Describe the bug**
auto future = fg_->WaitForFrame();  Unable to obtain frame after running function
**To Reproduce**
    std::string camera_ip = "169.254.50.239";
    int camera_port = 80;  // 假设相机的端口号是80
 
    auto cam = ifm3d::Device::MakeShared(camera_ip, camera_port); 
    auto fg = std::make_shared<ifm3d::FrameGrabber>(cam, 50010);
 
    fg->Start({ ifm3d::buffer_id::AMPLITUDE_IMAGE, ifm3d::buffer_id::RADIAL_DISTANCE_IMAGE, ifm3d::buffer_id::XYZ });
 
    pcl::visualization::CloudViewer viewer("Real-time Point Cloud Viewer");
 
    while (!viewer.wasStopped()) {
        auto frame = fg->WaitForFrame().get();
        ifm3d::Buffer xyz = frame->GetBuffer(ifm3d::buffer_id::XYZ);
 
        // ifm3d库从相机缓冲器获取的XYZ数据!!!!!
        ifm3d::Buffer_<ifm3d::Point3D_16S>  xyz_data = xyz;
 
        // Create a Point Cloud object
        pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
 
        // Populate the Point Cloud with XYZ data
        for (const auto& point : xyz_data)
        {
            pcl::PointXYZ pcl_point;
            pcl_point.x = point.val[1];
            pcl_point.y = point.val[2];
            pcl_point.z = point.val[0];
            cloud->push_back(pcl_point);
        }
 
        pcl::io::savePCDFileASCII("point_cloud.pcd", *cloud);
 
     
        viewer.showCloud(cloud);
    }

**Expected behavior**

**Output/Screenshots**
If applicable, add console output and/or screenshots to help explain your problem.

**Minimal Working Example**
If applicable/possible, please provide a [minimal working example](https://stackoverflow.com/help/minimal-reproducible-example) which demonstrates the problem and can be run standalone.

```
#include <iostream>
int main()
{
  std::cout << "Hello World!" << std::endl;
  return 0;
}
```

**Configuration/Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04, Windows 10]
 -  ifm3d version: [e.g. 0.14.0]
 - using ROS: [yes/no]

**Camera Configuration**
Please include the output of `ifm3d dump`

**Additional context**

**Comment by lola-masson** [comment]
Could you please share the version of ifm3d you are using, and the current configuration of the device (the result of ifm3d dump). Thanks

**Comment by Ken-Jia** [comment]
I did not notice the cam；but the fg->isRunning
() is
True

**Comment by Ken-Jia** [comment]
I try cam->Get() But cam does not have this function ;I try cam ->WhoAmI() output O3D

**Comment by lola-masson** [comment]
I'm sorry that's my bad, for the O3D it is cam->ToJSON().

**Comment by Ken-Jia** [comment]
I have anther question ； how to  using c++ code  to change  the camera trigger mode
