### ISSUE TITLE
json regression

### ISSUE THREAD

**Issue by jChaudet** [ifm/ifm3d#46]
For now, ifm3d doesn't support modern gcc (7.2) due to a regression in json library.
https://github.com/nlohmann/json/issues/590
https://stackoverflow.com/questions/44367859/using-stdarray-and-using-array-as-name

This corrects the problem.
```
/modules/camera/include/ifm3d/contrib/json.hpp
@@ -6083,7 +6083,7 @@ class basic_json
             {
                 case value_t::array:
                 {
-                    return *lhs.m_value.array < *rhs.m_value.array;
+                    return (*lhs.m_value.array) < *rhs.m_value.array;
                 }
```

**Comment by theseankelly** [comment]
Closing out old issues. ifm3d now builds on 18.04 using gcc 7.4 so I presume this has been fixed some time ago. Feel free to reactivate if this is still an issue.
