### ISSUE TITLE
Windows deployment XMLRPC errors

### ISSUE THREAD

**Issue by nayan27** [ifm/ifm3d#54]
Hi,

i followed the Windows deployment procedure (doc/windows.md). I got to a problem when attempting to build the ifm3d project.

The problem seemed related to XMLRPC files not found. Is there an environment variable to set about this ?

Thanks,

**Comment by graugans** [comment]
@nayan27 is this issue still present?

**Comment by nayan27** [comment]
I was able to get passed this problem but i can't recall exactly how as this happenned quite some time ago.

thank you thought!

**Comment by inbangsa** [comment]
@nayan27 I checked this with all the combinations of VS2015 and VS2017 with WIndows 8 and windows 10.  No issue found. 

can we close this issue ?
