### ISSUE TITLE
Adding support for intrinsic calibration

### ISSUE THREAD

**Issue by graugans** [ifm/ifm3d#62]
Firmware versions >= 1.23.x do support requesting of the intrinsic calibration by PCIC. To achieve this a new Chunk ID was introduced ``INTRINSIC_CALIBRATION  = 401`` This Chunk ID contains a string which is  JSON encoded with the following content:

```json
{
   "IntrinsicCalibration":{
      "TransRot":{
         "rotX":4.628749138647e-06,
         "rotY":1.82477015187e-05,
         "rotZ":-0.005543011706322,
         "transX":0.002997731789947,
         "transY":-0.003114672610536,
         "transZ":-0.01281386427581
      },
      "alpha":-0.0002843537949957,
      "fx":352.9755859375,
      "fy":353.9857788086,
      "k1":0.391823887825,
      "k2":0.4656725227833,
      "k3":8.726822852623e-05,
      "k4":0.001031797030009,
      "k5":-0.002137779723853,
      "mx":179.7865142822,
      "my":135.6101531982
   },
   "InverseIntrinsicCalibration":{
      "TransRot":{
         "rotX":0,
         "rotY":0,
         "rotZ":0,
         "transX":0,
         "transY":0,
         "transZ":0
      },
      "alpha":-0.0002843537949957,
      "fx":352.9755859375,
      "fy":353.9857788086,
      "k1":-0.4090084433556,
      "k2":0.1829420179129,
      "k3":-9.239422070095e-05,
      "k4":-0.0005769815179519,
      "k5":-0.03443950414658,
      "mx":179.7865142822,
      "my":135.6101531982
   }
}
```
This is an exclusive O3D3xx feature.

**Comment by Arag24** [comment]
I would love you and this firmware ... Interested to get it for many sensor app...

**Comment by graugans** [comment]
@Arag24 As you can see there is a new PR which provides this feature. But we use a [enum](https://github.com/lovepark/ifm3d/blob/3d86125b39f0cebc9107de6d42dc0794d9b97f68/modules/framegrabber/include/ifm3d/fg/byte_buffer.h#L73) used as a index into the ``std::vector`` returned by   [ std::vector<float> Intrinsics();](https://github.com/lovepark/ifm3d/blob/3d86125b39f0cebc9107de6d42dc0794d9b97f68/modules/framegrabber/include/ifm3d/fg/byte_buffer.h#L309) instead of the JSON object.

**Comment by alfatave** [comment]
HI all, it is a while that I'm trying to access to intrinsic parameters but unsuccessfully. The vector returned is composed by zeros, can suggest me the way to access to the right parameters?
Thank you!

**Comment by graugans** [comment]
@alfatave what camera firmware software version are you running on your device?

**Comment by alfatave** [comment]
@graugans thanks for the fast reply!
This morning I've updated the firmware, now it is: IFM_Software: 1.30.4123
I've also installed the last ifm3d release (using apt): ifm3d: version=0.14.1

I've tried with an older version from you (feature/152561-1 suggested a while ago from Italian support and the feature/intrinsic) but also in these cases I wasn't able to retrieve data.

**Comment by inbangsa** [comment]
@alfatave can you please check your schema that you are sending to ifm3d::framegrabber object constructor.

To get the particular type of data you need to configure schema. In your case it should have ifm3d::INTR_CAL

**Comment by alfatave** [comment]
@inbangsa @graugans Thanks a lot!! Now it works!!!
